### ISSUE TITLE
2015 postseason schedule

### ISSUE THREAD

**Issue by andr3w321** [BurntSushi/nfldb#134]
It's been released http://www.nfl.com/news/story/0ap3000000616555/article/nfl-playoff-schedule-released but maybe not in the format that nfldb pulls it from?  I've ran nfldb-update but I don't see any 2015 postseason games in the db.

**Comment by andr3w321** [comment]
This is the url we need to grab http://www.nfl.com/ajax/scorestrip?season=2015&week=18&seasonType=POST

**Comment by BurntSushi** [comment]
This should be fixed now. You'll need to run `pip install --uprade nfldb`.

FYI, this is actually an issue in `nflgame`. It requires manually switching the schedule URL every year. See this commit: https://github.com/BurntSushi/nflgame/commit/d5ca999fc061ee6063a73d397ef13e4f11177741 Once `nflgame` is fixed, `nfldb` should be updated to require the latest version of `nflgame` so that when you update `nfldb`, you'll get the latest `nflgame` automatically. Then simply run `nfldb-update` and you should have the postseason games in your DB.

**Comment by andr3w321** [comment]
I'm having trouble getting all the 2015 postseason games loaded.  I have two versions of nfldb running on difference computers.  One is an exact copy of your version and regularly runs nfldb upgrade and update.  It has postseason for week 1 and week 2 and has the following error that looks like a utf-8 encoding error.

```
$ nfldb-update 
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2016-01-28 14:24:29.944773
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Adding schedule data for 3 games... done.
Bulk inserting data for 6 games...
	Sending batch of data to database.
Traceback (most recent call last):
  File "/home/jane/.local/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 535, in run
    doit()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 195, in bulk_insert_game_data
    do()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 188, in do
    nfldb.db._big_insert(cursor, table, bulk[table])
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in _big_insert
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in <genexpr>
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 231, in _mogrify
    return cursor.mogrify('%s', (tuple(xs),))
  File "/home/jane/.local/lib/python2.7/site-packages/psycopg2/extensions.py", line 134, in getquoted
    qobjs = [o.getquoted() for o in pobjs]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 20: ordinal not in range(128)
```

```
select week,away_team,home_team from game where season_type = 'Postseason' and season_year = 2015;
 week | away_team | home_team 
------+-----------+-----------
    1 | KC        | HOU
    1 | PIT       | CIN
    1 | SEA       | MIN
    1 | GB        | WAS
    2 | KC        | NE
    2 | GB        | ARI
    2 | SEA       | CAR
    2 | PIT       | DEN
(8 rows)
```

A modified version of mine of nfldb which I run locally and update not so often is only missing week 2.
```
select week,away_team,home_team from game where season_type = 'Postseason' and season_year = 2015;
 week | away_team | home_team 
------+-----------+-----------
    1 | GB        | WAS
    1 | KC        | HOU
    1 | PIT       | CIN
    1 | SEA       | MIN
    3 | NE        | DEN
    3 | ARI       | CAR
    4 | CAR       | DEN
(7 rows)
```

nfldb-update seems to run fine on this machine

**Comment by andr3w321** [comment]
For my local machine I get the following nflgame error
```
$ nflgame-update-players --phase POST --year 2015 --week 2
Loading games for POST 2015 week 2
Traceback (most recent call last):
  File "/home/dan/.local/bin/nflgame-update-players", line 4, in <module>
    nflgame.update_players.run()
  File "/home/dan/.local/lib/python2.7/site-packages/nflgame/update_players.py", line 377, in run
    games = nflgame.games(year, week, kind=phase)
  File "/home/dan/.local/lib/python2.7/site-packages/nflgame/__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not iterable
```
I can run week 1,3,4 no problem.

**Comment by andr3w321** [comment]
I was able to get all the games on my local machine by running `~/.local/lib/python2.7/site-packages/nflgame$ python update_sched.py --rebuild` and `nfldb-update`  I'm still getting the unicode error on my server though.  Any ideas on how to fix that would be great.
